- src/main/java/ch/uzh/ifi/hase/soprafs22/constant/Gender.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/controller/UserController.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/entity/User.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/repository/UserRepository.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/rest/dto/UserPostDTO.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/rest/mapper/DTOMapper.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/service/UserService.java
- src/test/java/ch/uzh/ifi/hase/soprafs22/repository/UserRepositoryIntegrationTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs22/rest/mapper/DTOMapperTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs22/service/UserServiceIntegrationTest.java
added registration procedure to server
as well as changed user intentity.
pdate userPostDTO
> 13 registered user can log in and out in their profile server

- src/main/java/ch/uzh/ifi/hase/soprafs22/controller/UserController.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/service/UserService.java
- src/test/java/ch/uzh/ifi/hase/soprafs22/controller/UserControllerTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs22/service/UserServiceTest.java
added test for login of user:
- login success
- login fails
- servicecontrol checkpassword
> Added Tests for login for line coverage

- .github/workflows/deploy.yml
- src/main/java/ch/uzh/ifi/hase/soprafs22/Application.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/controller/UserController.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/entity/User.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/repository/UserRepository.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/rest/dto/UserGetDTO.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/rest/dto/UserPutDTO.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/rest/mapper/DTOMapper.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/service/UserService.java
- src/test/java/ch/uzh/ifi/hase/soprafs22/controller/UserControllerTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs22/service/UserServiceTest.java
Implement Rest Interface for Frontend (until now)
> 22 logged in user cant edit the personal data of any other account

- src/main/java/ch/uzh/ifi/hase/soprafs22/constant/Gender.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/entity/User.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/rest/dto/UserGetDTO.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/rest/dto/UserPostDTO.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/rest/mapper/DTOMapper.java
- src/test/java/ch/uzh/ifi/hase/soprafs22/controller/UserControllerTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs22/rest/mapper/DTOMapperTest.java
Created User now has correct Gender and Birthday assigned
> 53 user must give birthday and gender when logging in

- src/main/java/ch/uzh/ifi/hase/soprafs22/entity/Game.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/repository/GameRepository.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/service/GameService.java
- src/test/java/ch/uzh/ifi/hase/soprafs22/service/GameServiceTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs22/service/UserServiceIntegrationTest.java
Line coverage GameService class is now 96%
fixed some minor bugs
> 101 add testcases to server gameservice

- src/main/java/ch/uzh/ifi/hase/soprafs22/controller/GameController.java
- src/test/java/ch/uzh/ifi/hase/soprafs22/controller/GameControllerTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs22/service/UserServiceTest.java
finally done :)
100% code coverage for game controller and minor bug fixes / other tests
> 85 add testcases to server gamecontroller

- src/main/java/ch/uzh/ifi/hase/soprafs22/controller/GameController.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/service/UserService.java
- src/test/java/ch/uzh/ifi/hase/soprafs22/controller/GameControllerTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs22/controller/UserControllerTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs22/service/UserServiceTest.java
@JoMuelle I hope the changes I made are okay for you..
@TwoDigitsOneNumber could you do the merge? I'm afraid it does the weird thing again and your work of sorting it out this afternoon is in vain..
> 100 add testcases to server user service

- src/main/java/ch/uzh/ifi/hase/soprafs22/controller/GameController.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/service/GameService.java
- src/test/java/ch/uzh/ifi/hase/soprafs22/service/GameServiceTest.java
Server throws: 404 not Found No: "There is no black card of another user left" when the number of games of other users is 0
> 79 black card error when noleft

- src/test/java/ch/uzh/ifi/hase/soprafs22/service/GameServiceIntegrationTest.java
added integration test for createGame and putPlayinGame in GameServieIntegration test
> added integrationTests to GameServiceIntegrationTest

- src/main/java/ch/uzh/ifi/hase/soprafs22/controller/UserController.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/rest/dto/UserGetDTO.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/service/UserService.java
implemented api according to google sheets https://docs.google.com/spreadsheets/d/1YOr29j0gQqa2Qz562hBfuy-4WK2rcYtldDeSnlX2MjU/edit#gid=0
> 115 matches api

- src/main/java/ch/uzh/ifi/hase/soprafs22/controller/GameController.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/controller/UserController.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/entity/Game.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/entity/User.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/service/GameService.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/service/UserService.java
3 demo users added. they have the same password as the name
demoUser1, demoUser2, demoUser3
> 114 add demo users

- src/main/java/ch/uzh/ifi/hase/soprafs22/controller/ChatController.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/entity/Message.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/rest/dto/chat/ChatOverViewGetDTO.java
return match creation and increae content length
> return match Creation date

- src/main/java/ch/uzh/ifi/hase/soprafs22/entity/Match.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/service/UserService.java
> Bug fix that User can't have more than one Match

- src/main/java/ch/uzh/ifi/hase/soprafs22/entity/User.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/repository/GameRepository.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/service/GameService.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/service/UserService.java
-Filter for Userpreferences (Age + Gender)
> 134 filter presented black cards by gender preferences + age preference

- src/main/java/ch/uzh/ifi/hase/soprafs22/entity/User.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/repository/GameRepository.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/service/GameService.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/service/UserService.java
Reverts sopra-fs22-group-07/server#180
> Revert "134 filter presented black cards by gender preferences + age preference"

- src/main/java/ch/uzh/ifi/hase/soprafs22/controller/GameController.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/service/UserService.java
backend to user is not able to chose another blackCard
> add backend for user can not choose another blackCard

- src/main/java/ch/uzh/ifi/hase/soprafs22/rest/dto/UserPutDTO.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/rest/mapper/DTOMapper.java
- src/test/java/ch/uzh/ifi/hase/soprafs22/controller/UserControllerTest.java
-Very Small, only deleted ID from Put DTO
> -Deleted ID from UserPutDto + fixed tests

- src/main/java/ch/uzh/ifi/hase/soprafs22/repository/BlackCardRepository.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/repository/WhiteCardRepository.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/service/GameService.java
- src/test/java/ch/uzh/ifi/hase/soprafs22/service/GameServiceTest.java
Fixed Bug where the Cards you'd recieve be really similar.
> -White Cards and Black Cards now are more randomly distributed

- src/main/java/ch/uzh/ifi/hase/soprafs22/controller/GameController.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/repository/GameRepository.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/service/GameService.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/service/UserService.java
1) bugfix: past games get deleted when nobody played on them
2) blocked users can not play each other anymore
> 155 when a user is blocked their black cards dont show up for the other user anymore

- src/main/java/ch/uzh/ifi/hase/soprafs22/controller/ChatController.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/controller/UserController.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/entity/BlockedUserRelation.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/entity/Match.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/entity/User.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/repository/GameRepository.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/repository/MatchRepository.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/rest/dto/UserGetDetailsDTO.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/rest/mapper/DTOMapper.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/service/GameService.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/service/UserService.java
- src/test/java/ch/uzh/ifi/hase/soprafs22/controller/ChatControllerTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs22/controller/UserControllerTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs22/service/GameServiceTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs22/service/UserServiceTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs22/testHelpers/ChatFiller.java
closes #193 
closes #214 
closes #215 
Tests do now work yet @serainaschraff Can you fix them?
Please test in frontend thoroughly.
Solved by correctly mapping the relationships between the entities.
> Bugfix on deleting user

- src/main/java/ch/uzh/ifi/hase/soprafs22/controller/UserController.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/service/UserService.java
- src/test/java/ch/uzh/ifi/hase/soprafs22/controller/UserControllerTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs22/service/UserServiceTest.java
please check if this is alright :)
> added tests for location

- src/main/java/ch/uzh/ifi/hase/soprafs22/controller/UserController.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/service/UserService.java
- src/test/java/ch/uzh/ifi/hase/soprafs22/controller/UserControllerTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs22/service/UserServiceTest.java
double checked all files but did not find many dublicates :)
> 206 double check methods and remove dublicates if possible

- src/main/java/ch/uzh/ifi/hase/soprafs22/controller/UserController.java
- src/main/java/ch/uzh/ifi/hase/soprafs22/rest/dto/LocationPutDTO.java
- src/test/java/ch/uzh/ifi/hase/soprafs22/controller/UserControllerTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs22/service/ChatServiceTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs22/service/UserServiceTest.java
fixed some tests, demo users still not covered
> Testing again
